image: node:18.15.0

# Workflow Configuration

pipelines:
  branches:
    develop:
      - step:
          name: Build and Deploy Develop
          deployment: develop
          #   clone:
          #      enabled: false
          script:
            - apt-get update
            - printenv > .env
            - npm install
            - npm run build
            - apt-get install -y zip
            - zip -r application.zip build scripts
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET_DEV
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP_NAME_DEV
                S3_BUCKET: $S3_BUCKET_DEV
                WAIT: 'true'
                COMMAND: 'deploy'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'

    master:
      - step:
          name: Build and Deploy Develop
          deployment: production
          #   clone:
          #      enabled: false
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r application.zip build scripts
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET_PROD
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP_NAME_PROD
                S3_BUCKET: $S3_BUCKET_PROD
                WAIT: 'true'
                COMMAND: 'deploy'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
