// export interface CoverageDto {
//   id: number
//   special: boolean
//   coverage: string
// }

// Generated by https://quicktype.io

export interface CoverageDto {
  id: number;
  coverage: string;
  createdAt: string;
  updatedAt: string;
  active: boolean;
  yesAndLuc: boolean;
  coverageTypeId: CoverageTypeID;
  coverageTypeName?: string
}

export interface CoverageTypeID {
  id: number;
  name: string;
  createdAt: string;
  active: boolean;
}


export interface CoverageInputDto {
  coverage: string,
  yesAndLuc: boolean,
  coverageType: string,
  accountId: number | any
}
