const data = [
    {
      id:'0001',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0002',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0003',
      status:'bound',
      insured:'Jordan Stevenson',
      lob:'Financial lines',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0004',
      status:'bound',
      insured:'Jordan Stevenson',
      lob:'Financial lines',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0005',
      status:'declined',
      insured:'Jordan Stevenson',
      lob:'Financial lines',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0006',
      status:'declined',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0007',
      status:'notMaterialized',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0008',
      status:'notMaterialized',
      insured:'Jordan Stevenson',
      lob:'Financial lines',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0009',
      status:'notTakenUp',
      insured:'Jordan Stevenson',
      lob:'Financial lines',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0010',
      status:'notTakenUp',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0011',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0012',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0013',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0014',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0015',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0016',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0017',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0018',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0019',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
    {
      id:'0020',
      status:'pending',
      insured:'Jordan Stevenson',
      lob:'Property',
      effectiveDate:'18 Oct 2022',
      expirationDate:'18 Oct 2023',
    },
  ]

export default data